### ISSUE TITLE
Fel problem (ubuntu)

### ISSUE THREAD

**Issue by loicbonino** [Thore-Krug/Flash-CHIP#6] opened 2019-04-17 12:03 UTC
I have the same error with ubuntu, the chip is in FEL mode ( the pins are connected) it’s in a usb2 port with a working cable, but it keeps saying : waiting for Fel:.......... timeout

**Comment by Thore-Krug** [comment] 2019-04-18 20:39
Ok please remove the old repo with  ``` rm -r *Path to Folder * ```
 then run ```git clone -b Thore-Krug1 https://github.com/Thore-Krug/Flash-CHIP.git ```
( This downloads a slightly changed version )
Insert your Chip to your PC make sure u have a wire between Ground and FEl. 

then  change into the Folder ```cd Flash-Chip ```
make the file executeable ```sudo chmod +x Flash.sh ```
run the script ```sudo ./Flash.sh ```
 If the error still appears run ```lsusb ``` before and after u pluged in your Chip and look if a new device  show up ( for example Tablet in Flashing mode or USB composit gadet ) . Then run  ``` dmesg ``` too and attached the output here as File.

**Comment by Thore-Krug** [comment] 2019-04-25 23:44
@loicbonino Any Progress ? Otherwise i consider to close this issue.

**Comment by loicbonino** [comment] 2019-04-26 13:05
My chip is dead i think, you can close this, i thank you for trying

**Comment by Thore-Krug** [comment] 2019-04-26 13:38
Did u tried my commands ?

**Closed as completed** 2019-04-27 14:19 UTC

**Comment by 96fps** [comment] 2019-07-15 19:20
I'm afraid I'm encountering this aswell with two of my CHIP's, it used to be one but after my CHIP's sat in a box for months I unsuccessfully tried to flash from a Linux VirtualBox machine on windows by sharing USB devices. Now both fail on a native Ubuntu 19.04 machine.

Edit: will be trying different cables to see if that has any effect

**Comment by Thore-Krug** [comment] 2019-07-15 19:38
Did u connected a wire between FEL and Ground ? Did u double checked your cable ? Disabled power saving ? What does the command lsusb output when the chip is plugged into your PC ?

**Comment by 96fps** [comment] 2019-07-15 19:42
I am shorting the FEL header with ground, the cable is a data cable. I'm using a powered hub and even plugged the chip into the battery of a disassembled pocketchip after reading another thread.
lsusb lists the chip as `Bus 002 Device 014: ID 1f3a:efe8 Onda (unverified) V972 tablet in flashing mode`

**Comment by 96fps** [comment] 2019-07-15 19:44
one of my chips passes this step and is tripped up immediately after with error -7
```
 Installing CHIP-tools
Already up to date.
== Pocketchip selected ==
== preparing images ==
== Local/cached probe files located ==
== Staging for NAND probe ==
Image Name:   detect NAND
Created:      Mon Jul 15 15:28:35 2019
Image Type:   ARM Linux Script (uncompressed)
Data Size:    97 Bytes = 0.09 KiB = 0.00 MiB
Load Address: 00000000
Entry Point:  00000000
Contents:
   Image 0: 89 Bytes = 0.09 KiB = 0.00 MiB
waiting for fel...OK
usb_bulk_send() ERROR -7: Operation timed out
```
but my other seems to get stuck at `waiting for fel...........`

**Comment by 96fps** [comment] 2019-07-15 19:47
I'm using a new wire to short to fel, and power-cycled the chip once more, now it also reaches error -7

**Comment by Thore-Krug** [comment] 2019-07-15 19:55
Error -7 is a libusb problem which is mostly caused by bad cables unfortunately the chip is quit sensitive.  And are u Shure your USB port can deliver enough current ? Also use usb2 usb3 causes a lot of problems

**Comment by bestouff** [comment] 2020-05-19 12:06
What if I have only USB3 ports ?

**Comment by Thore-Krug** [comment] 2020-05-19 12:25
You can try a Usb2 hub or just give it a shot on USB3

**Comment by bestouff** [comment] 2020-05-19 13:09
Well I have this exact same problem:
```
waiting for fel......OK
usb_bulk_send() ERROR -7: Operation timed out
```
I'll try to find a hub somewhere.

**Comment by Emzy** [comment] 2020-05-24 13:57
Same here. Also with a powered hub. And different cables. 
Also same on 3 different C.H.I.P's and on a Debian VM and a Raspbery PI4

**Comment by bestouff** [comment] 2020-05-25 08:32
Yeah, it didn't work for me with a usb2 hub also.

**Comment by Emzy** [comment] 2020-05-25 13:52
> Yeah, it didn't work for me with a usb2 hub also.

Fix: https://github.com/Thore-Krug/Flash-CHIP/issues/21#issuecomment-625323920

**Comment by Thore-Krug** [comment] 2020-05-25 14:03
The Chip is very finiky about cables and  USB timing a VM is very suboptimal. Also I created a Live Linux to flash your Chip from multiple people tried it and it worked flawlessly. Will put the link and instructions here soon.

**Comment by bestouff** [comment] 2020-05-25 14:11
> > Yeah, it didn't work for me with a usb2 hub also.
> 
> Fix: #21

Indeed ! Did someone open a bugreport against sunxi-tools ?

**Comment by DYoshihiro** [comment] 2020-07-02 08:06
I'm not sure you guys are still here, but I solved this issue.

> Error -7 is a libusb problem which is mostly caused by bad cables unfortunately the chip is quit sensitive. And are u Shure your USB port can deliver enough current ? Also use usb2 usb3 causes a lot of problems

> Well I have this exact same problem:
> 
> ```
> waiting for fel......OK
> usb_bulk_send() ERROR -7: Operation timed out
> ```
> 
> I'll try to find a hub somewhere.

I had a same problem, so I tried following method,

https://medium.com/@0x1231/nextthingco-pocket-c-h-i-p-flashing-guide-3445492639e

but I got following errors.
```
fatal error: stdint.h: No such file or directory
fatal error: assert.h: No such file or directory
fatal error: ctype.h: No such file or directory
```
so I did this ```sudo apt install --reinstall build-essential```

...and I got another errors.
```
fatal error: fatal error: zlib.h: No such file or directory
fatal error: libusb.h: No such file or directory
```

...so I did these.
```
sudo apt-get install zlib1g-dev
sudo apt-get install libusb-1.0-0-dev
```
Finally, -7 error is solved and Flash-CHIP is working for me, I can use my Pocket C.H.I.P. again!!

optional:
I also tried these but I'm not sure if it's necessary.
```
sudo apt-get install avr-libc
sudo apt install --reinstall gcc-5.4
```

**Comment by DYoshihiro** [comment] 2020-07-02 08:08
oh and I was using USB3 without battery

**Comment by satish-hsk** [comment] 2020-11-26 05:56
I had the same issue "usb_bulk_send() ERROR -7: Operation timed out"
Following the above mentioned link https://medium.com/@0x1231/nextthingco-pocket-c-h-i-p-flashing-guide-3445492639e also solved and recovered my CHIP.  (after being in my closet for more than one year)

**Comment by necarnot** [comment] 2021-06-22 08:22
> The Chip is very finiky about cables and USB timing a VM is very suboptimal. Also I created a Live Linux to flash your Chip from multiple people tried it and it worked flawlessly. Will put the link and instructions here soon.

Hello @Thore-Krug , 
As I'm facing the same issue (FEL timeout) and though I've tried every proposed workaround to no avail, I'd be glad to know if you could provide the Live Linux you were talking about?

Thank you

Nicolas
